// src/lib/mockData.ts
import { 
  User, 
  MedicalRecord, 
  HealthAnalytics, 
  Prescription, 
  Village, 
  Worker, 
  OutbreakAlert, 
  PredictedOutbreak, 
  Referral, 
  CareCoordinationTask,
  ConflictRecord
} from '../types';

export const INITIAL_VILLAGES: Village[] = [
  { name: 'Alur', lat: 15.123, lng: 77.123, patient_count: 120, high_risk_count: 15, emergency_cases: 2, worker_count: 3, avg_risk_score: 48, last_activity: new Date().toISOString() },
  { name: 'Gooty', lat: 15.234, lng: 77.234, patient_count: 85, high_risk_count: 8, emergency_cases: 0, worker_count: 2, avg_risk_score: 32, last_activity: new Date().toISOString() },
  { name: 'Adoni', lat: 15.345, lng: 77.345, patient_count: 200, high_risk_count: 35, emergency_cases: 5, worker_count: 5, avg_risk_score: 68, last_activity: new Date().toISOString() },
  { name: 'Dhone', lat: 15.456, lng: 77.456, patient_count: 150, high_risk_count: 20, emergency_cases: 1, worker_count: 4, avg_risk_score: 52, last_activity: new Date().toISOString() },
  { name: 'Pattikonda', lat: 15.567, lng: 77.567, patient_count: 95, high_risk_count: 12, emergency_cases: 0, worker_count: 2, avg_risk_score: 41, last_activity: new Date().toISOString() },
];

export const INITIAL_WORKERS: Worker[] = [
  { id: 'w1', name: 'Anitha K.', village: 'Alur', phone: '+91 98765 43210', lat: 15.125, lng: 77.125, last_sync: new Date(Date.now() - 15 * 60 * 1000).toISOString(), status: 'Active', assigned_patients: 40, visits_this_week: 14, overdue_patients: 2, emergencies_handled_30d: 4 },
  { id: 'w2', name: 'Lakshmi P.', village: 'Adoni', phone: '+91 98765 43211', lat: 15.348, lng: 77.348, last_sync: new Date(Date.now() - 45 * 60 * 1000).toISOString(), status: 'Active', assigned_patients: 45, visits_this_week: 18, overdue_patients: 5, emergencies_handled_30d: 8 },
  { id: 'w3', name: 'Rani M.', village: 'Dhone', phone: '+91 98765 43212', lat: 15.458, lng: 77.458, last_sync: new Date(Date.now() - 120 * 60 * 1000).toISOString(), status: 'Idle', assigned_patients: 38, visits_this_week: 9, overdue_patients: 1, emergencies_handled_30d: 2 },
  { id: 'w4', name: 'Sunita B.', village: 'Pattikonda', phone: '+91 98765 43213', lat: 15.569, lng: 77.569, last_sync: new Date(Date.now() - 10 * 60 * 1000).toISOString(), status: 'Active', assigned_patients: 32, visits_this_week: 11, overdue_patients: 0, emergencies_handled_30d: 1 },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-101',
    name: 'Ramesh Kumar',
    age: 58,
    gender: 'Male',
    preferred_language: 'Hindi',
    phone: '+91 98234 11021',
    village: 'Adoni',
    household_id: 'HH-AD-042',
    address: 'Near Old Water Tank, Ward 4, Adoni',
    blood_group: 'B+',
    emergency_contact: '+91 98234 11022 (Son: Ajay)',
    lat: 15.346,
    lng: 77.346,
    created_at: '2026-08-10T10:00:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-30T07:30:00Z'
  },
  {
    id: 'u-102',
    name: 'Sunita Devi',
    age: 49,
    gender: 'Female',
    preferred_language: 'Hindi',
    phone: '+91 98234 11023',
    village: 'Alur',
    household_id: 'HH-AL-019',
    address: 'Main Bazaar Lane, Alur',
    blood_group: 'O+',
    emergency_contact: '+91 98234 11024 (Husband: Mohan)',
    lat: 15.124,
    lng: 77.124,
    created_at: '2026-08-15T11:20:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-29T18:00:00Z'
  },
  {
    id: 'u-103',
    name: 'Venkatesh Rao',
    age: 67,
    gender: 'Male',
    preferred_language: 'Marathi',
    phone: '+91 98234 11025',
    village: 'Adoni',
    household_id: 'HH-AD-088',
    address: 'Kalyan Nagar, Adoni',
    blood_group: 'A+',
    emergency_contact: '+91 98234 11026 (Daughter: Kavita)',
    lat: 15.349,
    lng: 77.349,
    created_at: '2026-07-20T09:15:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-30T06:15:00Z'
  },
  {
    id: 'u-104',
    name: 'Fatima Begum',
    age: 38,
    gender: 'Female',
    preferred_language: 'Hindi',
    phone: '+91 98234 11027',
    village: 'Dhone',
    household_id: 'HH-DH-102',
    address: 'Behind Community Hall, Dhone',
    blood_group: 'AB+',
    emergency_contact: '+91 98234 11028 (Brother: Imran)',
    lat: 15.457,
    lng: 77.457,
    created_at: '2026-09-01T14:40:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-28T16:00:00Z'
  },
  {
    id: 'u-105',
    name: 'Suresh Patil',
    age: 62,
    gender: 'Male',
    preferred_language: 'Marathi',
    phone: '+91 98234 11029',
    village: 'Pattikonda',
    household_id: 'HH-PK-055',
    address: 'Near Gram Panchayat, Pattikonda',
    blood_group: 'O-',
    emergency_contact: '+91 98234 11030 (Wife: Shobha)',
    lat: 15.568,
    lng: 77.568,
    created_at: '2026-08-28T08:30:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-29T12:00:00Z'
  },
  {
    id: 'u-106',
    name: 'Lakshmi Bai',
    age: 72,
    gender: 'Female',
    preferred_language: 'Hindi',
    phone: '+91 98234 11031',
    village: 'Gooty',
    household_id: 'HH-GT-012',
    address: 'Station Road, Gooty',
    blood_group: 'B-',
    emergency_contact: '+91 98234 11032 (Son: Rajesh)',
    lat: 15.235,
    lng: 77.235,
    created_at: '2026-06-12T16:10:00Z',
    consent_status: 'granted',
    last_diary_sync: '2026-09-27T10:00:00Z'
  }
];

export const INITIAL_ANALYTICS: HealthAnalytics[] = [
  {
    id: 'a-101',
    user_id: 'u-101',
    vaccination_status: 'Completed',
    vaccination_label: 'Fully Vaccinated (Booster 2024)',
    medicine_tracker: 'Taking Daily',
    medicine_percent: '86%',
    medicine_progress: 86,
    last_checkup_date: '2026-09-20',
    last_checkup_status: 'High BP Recorded (168/102)',
    next_appointment_doctor: 'Dr. Arvind Sharma (CHC Adoni)',
    next_appointment_date: '2026-10-04',
    risk_score: 84,
    risk_level: 'High',
    risks: ['Severe Hypertension (+22)', 'Age 58 (+10)', 'Pre-existing CAD (+25)', 'Low adherence last week (+8)'],
    weekly_summary: 'Patient experiencing exertional dyspnea and morning occipital headaches. High systolic spike.',
    systolic_bp: 168,
    diastolic_bp: 102,
    spo2: 93,
    heart_rate: 88,
    blood_glucose: 195,
    adherence_rate: 86,
    missed_followups: 1,
    has_diabetes: true,
    has_hypertension: true,
    has_cardiac_history: true,
    other_chronic_conditions: ['Stage 2 Hypertension', 'Type 2 Diabetes', 'Ischemic Heart Disease'],
    emergency_flag: false,
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-30T07:30:00Z'
  },
  {
    id: 'a-102',
    user_id: 'u-102',
    vaccination_status: 'Completed',
    vaccination_label: 'Up to Date',
    medicine_tracker: 'Irregular',
    medicine_percent: '58%',
    medicine_progress: 58,
    last_checkup_date: '2026-09-25',
    last_checkup_status: 'Fever and Joint Pain',
    next_appointment_doctor: 'Dr. Priya Mehta (PHC Alur)',
    next_appointment_date: '2026-10-02',
    risk_score: 52,
    risk_level: 'Moderate',
    risks: ['High Fever 102.4F (+12)', 'Low Adherence (+18)', 'Joint Inflammation (+10)'],
    weekly_summary: 'Fever with chills and retro-orbital pain for 4 days. Tested negative for malaria, suspected viral/dengue.',
    systolic_bp: 124,
    diastolic_bp: 80,
    spo2: 97,
    heart_rate: 96,
    blood_glucose: 110,
    adherence_rate: 58,
    missed_followups: 2,
    has_diabetes: false,
    has_hypertension: false,
    has_cardiac_history: false,
    other_chronic_conditions: ['Osteoarthritis'],
    emergency_flag: false,
    created_at: '2026-09-25T11:20:00Z',
    updated_at: '2026-09-29T18:00:00Z'
  },
  {
    id: 'a-103',
    user_id: 'u-103',
    vaccination_status: 'Completed',
    vaccination_label: 'Up to Date',
    medicine_tracker: 'Regular',
    medicine_percent: '92%',
    medicine_progress: 92,
    last_checkup_date: '2026-09-29',
    last_checkup_status: 'SpO2 88% - Acute Respiratory Distress',
    next_appointment_doctor: 'Dr. Arvind Sharma (Emergency CHC)',
    next_appointment_date: '2026-09-30',
    risk_score: 94,
    risk_level: 'Critical',
    risks: ['CRITICAL: SpO2 88% (+35)', 'Elderly Age 67 (+18)', 'Acute Chest Tightness (+25)', 'Cardiac History (+25)'],
    weekly_summary: 'EMERGENCY: SpO2 dropped below 90% with progressive shortness of breath and chest pressure. Immediate oxygenation advised.',
    systolic_bp: 178,
    diastolic_bp: 108,
    spo2: 88,
    heart_rate: 112,
    blood_glucose: 240,
    adherence_rate: 92,
    missed_followups: 0,
    has_diabetes: true,
    has_hypertension: true,
    has_cardiac_history: true,
    other_chronic_conditions: ['COPD', 'Hypertensive Heart Disease', 'Type 2 Diabetes'],
    emergency_flag: true,
    emergency_reason: 'SpO2 88% with chest tightness and severe dyspnea',
    created_at: '2026-09-29T09:15:00Z',
    updated_at: '2026-09-30T06:15:00Z'
  },
  {
    id: 'a-104',
    user_id: 'u-104',
    vaccination_status: 'Completed',
    vaccination_label: 'Up to Date',
    medicine_tracker: 'Taking Daily',
    medicine_percent: '95%',
    medicine_progress: 95,
    last_checkup_date: '2026-09-18',
    last_checkup_status: 'Stable Routine Check',
    next_appointment_doctor: 'Dr. R. K. Varma (PHC Dhone)',
    next_appointment_date: '2026-10-18',
    risk_score: 22,
    risk_level: 'Low',
    risks: ['Mild Iron Deficiency Anemia (+10)', 'Good Adherence (95%)'],
    weekly_summary: 'Vitals stable. Hemoglobin improved from 9.2 to 10.8 g/dL with generic iron-folic acid supplementation.',
    systolic_bp: 118,
    diastolic_bp: 76,
    spo2: 99,
    heart_rate: 72,
    blood_glucose: 94,
    adherence_rate: 95,
    missed_followups: 0,
    has_diabetes: false,
    has_hypertension: false,
    has_cardiac_history: false,
    other_chronic_conditions: ['Mild Anemia'],
    emergency_flag: false,
    created_at: '2026-09-18T14:40:00Z',
    updated_at: '2026-09-28T16:00:00Z'
  },
  {
    id: 'a-105',
    user_id: 'u-105',
    vaccination_status: 'Partial',
    vaccination_label: 'Pending Booster',
    medicine_tracker: 'Missed 3 Doses',
    medicine_percent: '64%',
    medicine_progress: 64,
    last_checkup_date: '2026-09-22',
    last_checkup_status: 'High Fasting Sugar (265 mg/dL)',
    next_appointment_doctor: 'Dr. Priya Mehta (PHC Pattikonda)',
    next_appointment_date: '2026-10-06',
    risk_score: 66,
    risk_level: 'High',
    risks: ['Severe Hyperglycemia (+20)', 'Age 62 (+10)', 'Chronic Diabetes (+15)', 'Poor Adherence (+12)'],
    weekly_summary: 'Frequent nocturia, tingling in feet, fasting sugar 265 mg/dL. Skipped Metformin due to pharmacy stock-out.',
    systolic_bp: 144,
    diastolic_bp: 88,
    spo2: 96,
    heart_rate: 80,
    blood_glucose: 265,
    adherence_rate: 64,
    missed_followups: 1,
    has_diabetes: true,
    has_hypertension: true,
    has_cardiac_history: false,
    other_chronic_conditions: ['Type 2 Diabetes Mellitus', 'Diabetic Peripheral Neuropathy'],
    emergency_flag: false,
    created_at: '2026-09-22T08:30:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'a-106',
    user_id: 'u-106',
    vaccination_status: 'Completed',
    vaccination_label: 'Up to Date',
    medicine_tracker: 'Taking Daily',
    medicine_percent: '88%',
    medicine_progress: 88,
    last_checkup_date: '2026-09-15',
    last_checkup_status: 'General Geriatric Check',
    next_appointment_doctor: 'Dr. Arvind Sharma (CHC Gooty)',
    next_appointment_date: '2026-10-15',
    risk_score: 38,
    risk_level: 'Moderate',
    risks: ['Elderly Age 72 (+18)', 'Mild Hypertension (+12)', 'Controlled Glycemia'],
    weekly_summary: 'Blood pressure controlled on low-dose Amlodipine. No acute distress reported.',
    systolic_bp: 136,
    diastolic_bp: 82,
    spo2: 96,
    heart_rate: 74,
    blood_glucose: 132,
    adherence_rate: 88,
    missed_followups: 0,
    has_diabetes: false,
    has_hypertension: true,
    has_cardiac_history: false,
    other_chronic_conditions: ['Essential Hypertension', 'Mild Osteoporosis'],
    emergency_flag: false,
    created_at: '2026-09-15T16:10:00Z',
    updated_at: '2026-09-27T10:00:00Z'
  }
];

export const INITIAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-1',
    user_id: 'u-101',
    patient_name: 'Ramesh Kumar',
    report_type: 'Follow-up Checkup & Vitals',
    date: '2026-09-20',
    doctor: 'Dr. Arvind Sharma',
    hospital: 'CHC Adoni',
    status: 'Completed',
    details: 'Complained of morning occipital headaches and mild dizziness. Blood pressure measured at 168/102 mmHg. Heart sounds regular with no S3 gallop.',
    icon: 'medical_services',
    symptoms: ['Headache', 'Dizziness', 'Mild Chest Discomfort'],
    affected_body_zones: ['head', 'chest'],
    vitals: { systolic_bp: 168, diastolic_bp: 102, spo2: 93, temperature: 98.4, heart_rate: 88, blood_glucose: 195 },
    provisional_diagnosis: 'Uncontrolled Essential Hypertension with Type 2 Diabetes',
    created_at: '2026-09-20T10:00:00Z',
    created_by: 'w2',
    sync_status: 'synced'
  },
  {
    id: 'rec-2',
    user_id: 'u-103',
    patient_name: 'Venkatesh Rao',
    report_type: 'Emergency Field Triage',
    date: '2026-09-29',
    doctor: 'Dr. Arvind Sharma',
    hospital: 'Emergency CHC Adoni',
    status: 'Emergency Escalated',
    details: 'Worker Lakshmi P. arrived during home visit. Patient was gasping for breath, clutching left chest. SpO2 88%. Oxygen concentrator arranged; 108 ambulance called.',
    icon: 'healing',
    symptoms: ['Chest Pain', 'Severe Shortness of Breath', 'Cold Sweating'],
    affected_body_zones: ['chest', 'lungs', 'heart'],
    vitals: { systolic_bp: 178, diastolic_bp: 108, spo2: 88, temperature: 98.6, heart_rate: 112, blood_glucose: 240 },
    provisional_diagnosis: 'Acute Coronary Syndrome / Acute Exacerbation of COPD',
    created_at: '2026-09-29T09:15:00Z',
    created_by: 'w2',
    sync_status: 'synced'
  },
  {
    id: 'rec-3',
    user_id: 'u-102',
    patient_name: 'Sunita Devi',
    report_type: 'Viral Fever Screening',
    date: '2026-09-25',
    doctor: 'Dr. Priya Mehta',
    hospital: 'PHC Alur',
    status: 'Under Observation',
    details: 'Patient presented with sudden high fever (102.4F), body ache, and severe knee joint stiffness. Hydration advised. Prescribed Paracetamol.',
    icon: 'science',
    symptoms: ['High Fever', 'Body Ache', 'Joint Pain'],
    affected_body_zones: ['head', 'joints', 'legs'],
    vitals: { systolic_bp: 124, diastolic_bp: 80, spo2: 97, temperature: 102.4, heart_rate: 96, blood_glucose: 110 },
    provisional_diagnosis: 'Acute Febrile Illness / Suspected Arboviral Fever',
    created_at: '2026-09-25T11:20:00Z',
    created_by: 'w1',
    sync_status: 'synced'
  },
  {
    id: 'rec-4',
    user_id: 'u-105',
    patient_name: 'Suresh Patil',
    report_type: 'NCD Diabetic Review',
    date: '2026-09-22',
    doctor: 'Dr. Priya Mehta',
    hospital: 'PHC Pattikonda',
    status: 'Medication Adjusted',
    details: 'Random blood sugar 265 mg/dL. Patient reports burning sensation in soles of feet. Counseled on strict adherence to Metformin and dietary restriction.',
    icon: 'medical_services',
    symptoms: ['Frequent Urination', 'Tingling Feet', 'Excessive Thirst'],
    affected_body_zones: ['pancreas', 'legs', 'feet'],
    vitals: { systolic_bp: 144, diastolic_bp: 88, spo2: 96, temperature: 98.2, heart_rate: 80, blood_glucose: 265 },
    provisional_diagnosis: 'Uncontrolled Type 2 Diabetes with Diabetic Neuropathy',
    created_at: '2026-09-22T08:30:00Z',
    created_by: 'w4',
    sync_status: 'synced'
  }
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1',
    user_id: 'u-101',
    medical_record_id: 'rec-1',
    medicine_name: 'Telma 40 (Telmisartan)',
    generic_name: 'Telmisartan 40mg',
    dosage: '1 Tab Daily',
    timing: 'Morning',
    meal_timing: 'After breakfast',
    duration: '30 Days',
    generic_status: 'approved',
    brand_price: 185,
    generic_price: 24,
    savings: 161,
    created_at: '2026-09-20T10:00:00Z'
  },
  {
    id: 'rx-2',
    user_id: 'u-101',
    medical_record_id: 'rec-1',
    medicine_name: 'Glycomet 500 (Metformin)',
    generic_name: 'Metformin Hydrochloride 500mg',
    dosage: '1 Tab Twice Daily',
    timing: 'Morning / Night',
    meal_timing: 'After meals',
    duration: '30 Days',
    generic_status: 'approved',
    brand_price: 95,
    generic_price: 14,
    savings: 81,
    created_at: '2026-09-20T10:00:00Z'
  },
  {
    id: 'rx-3',
    user_id: 'u-101',
    medical_record_id: 'rec-1',
    medicine_name: 'Atorva 10 (Atorvastatin)',
    generic_name: 'Atorvastatin Calcium 10mg',
    dosage: '1 Tab Bedtime',
    timing: 'Night',
    meal_timing: 'Before sleep',
    duration: '30 Days',
    generic_status: 'approved',
    brand_price: 170,
    generic_price: 22,
    savings: 148,
    created_at: '2026-09-20T10:00:00Z'
  },
  {
    id: 'rx-4',
    user_id: 'u-103',
    medical_record_id: 'rec-2',
    medicine_name: 'Amlong 5 (Amlodipine)',
    generic_name: 'Amlodipine Besylate 5mg',
    dosage: '1 Tab Morning',
    timing: 'Morning',
    meal_timing: 'After breakfast',
    duration: '15 Days',
    generic_status: 'approved',
    brand_price: 65,
    generic_price: 9,
    savings: 56,
    created_at: '2026-09-29T09:15:00Z'
  },
  {
    id: 'rx-5',
    user_id: 'u-102',
    medical_record_id: 'rec-3',
    medicine_name: 'Calpol 650 (Paracetamol)',
    generic_name: 'Paracetamol 650mg',
    dosage: '1 Tab SOS',
    timing: 'When Fever > 100°F',
    meal_timing: 'After food',
    duration: '5 Days',
    generic_status: 'approved',
    brand_price: 35,
    generic_price: 6,
    savings: 29,
    created_at: '2026-09-25T11:20:00Z'
  }
];

export const INITIAL_REFERRALS: Referral[] = [
  {
    id: 'ref-1',
    user_id: 'u-103',
    patient_name: 'Venkatesh Rao',
    village: 'Adoni',
    priority: 'Emergency',
    specialty: 'Cardiology / Emergency Care',
    target_response_time: 'Immediate (< 1 Hour)',
    risk_score: 94,
    top_factors: ['SpO2 88% (Severe Hypoxemia)', 'Acute Chest Tightness', 'Age 67 with CAD History'],
    status: 'Created',
    worker_name: 'Lakshmi P.',
    created_at: '2026-09-29T09:20:00Z'
  },
  {
    id: 'ref-2',
    user_id: 'u-101',
    patient_name: 'Ramesh Kumar',
    village: 'Adoni',
    priority: 'Urgent',
    specialty: 'Internal Medicine / Cardiology',
    target_response_time: 'Within 24 Hours',
    risk_score: 84,
    top_factors: ['Stage 2 SBP 168 mmHg', 'Pre-existing CAD', 'Fasting Blood Glucose 195'],
    status: 'Synced',
    worker_name: 'Lakshmi P.',
    created_at: '2026-09-20T10:15:00Z'
  },
  {
    id: 'ref-3',
    user_id: 'u-105',
    patient_name: 'Suresh Patil',
    village: 'Pattikonda',
    priority: 'Urgent',
    specialty: 'Diabetology / Endocrinology',
    target_response_time: 'Within 48 Hours',
    risk_score: 66,
    top_factors: ['Blood Glucose 265 mg/dL', 'Diabetic Neuropathy Symptoms', 'Missed Doses'],
    status: 'Accepted',
    worker_name: 'Sunita B.',
    created_at: '2026-09-22T08:45:00Z',
    doctor_notes: 'Reviewed. Scheduled for HbA1c testing and foot examination on Tuesday.'
  }
];

export const INITIAL_OUTBREAKS: OutbreakAlert[] = [
  {
    id: 'o-1',
    symptom: 'Acute Febrile Illness & Arthralgia',
    patient_count: 14,
    center_lat: 15.348,
    center_lng: 77.348,
    radius_km: 12,
    severity: 'High',
    village_names: ['Adoni', 'Dhone'],
    time_window: 'Last 48 Hours',
    suggested_action: 'Deploy mobile fever screening unit, initiate larvicidal fogging, and test community drinking water sources.',
    created_at: '2026-09-28T10:00:00Z'
  },
  {
    id: 'o-2',
    symptom: 'Gastroenteritis / Acute Watery Diarrhea',
    patient_count: 8,
    center_lat: 15.124,
    center_lng: 77.124,
    radius_km: 8,
    severity: 'Moderate',
    village_names: ['Alur', 'Gooty'],
    time_window: 'Last 72 Hours',
    suggested_action: 'Distribute ORS and Zinc sachets at Anganwadi centers, chlorinate public borewells.',
    created_at: '2026-09-29T14:30:00Z'
  }
];

export const INITIAL_PREDICTIONS: PredictedOutbreak[] = [
  {
    id: 'p-1',
    disease: 'Vector-Borne Dengue / Chikungunya Surge',
    center_lat: 15.39,
    center_lng: 77.39,
    radius_km: 14,
    severity: 'High',
    confidence: 86,
    estimated_cases: 24,
    village_names: ['Adoni', 'Dhone'],
    signals: ['High-risk patient fever cluster detected', 'Post-monsoon water logging reported by ASHA workers', 'Worker visit density increased 40%'],
    suggested_action: 'Pre-position NS1 rapid test kits and IV fluids at CHC Adoni; alert vector control teams.',
    basis: 'ai_model'
  },
  {
    id: 'p-2',
    disease: 'Water-Borne Acute Gastroenteric Cluster',
    center_lat: 15.18,
    center_lng: 77.18,
    radius_km: 9,
    severity: 'Moderate',
    confidence: 72,
    estimated_cases: 12,
    village_names: ['Alur', 'Gooty'],
    signals: ['Sub-center reports 6 new pediatric dehydration cases', 'Borewell contamination flagged in South Alur'],
    suggested_action: 'Super-chlorination of overhead storage reservoirs and door-to-door ORS provisioning.',
    basis: 'ai_model'
  }
];

export const INITIAL_CARE_TASKS: CareCoordinationTask[] = [
  {
    id: 'task-1',
    user_id: 'u-103',
    patient_name: 'Venkatesh Rao',
    village: 'Adoni',
    priority: 'High',
    missing_data_fields: ['Recent Blood Glucose', 'Current Weight'],
    reason: 'Critical SpO2 88% and cardiac history recorded. Emergency handoff generated.',
    recommended_action: 'ASHA Lakshmi P. to confirm emergency transfer to CHC Adoni ICU and record transport vitals.',
    assigned_worker: 'Lakshmi P.',
    status: 'pending',
    created_at: '2026-09-29T09:25:00Z'
  },
  {
    id: 'task-2',
    user_id: 'u-102',
    patient_name: 'Sunita Devi',
    village: 'Alur',
    priority: 'Moderate',
    missing_data_fields: ['Platelet Count / Dengue Serology', 'Hydration Log'],
    reason: 'Fever 102.4F with joint pain in active outbreak zone.',
    recommended_action: 'Worker Anitha K. to collect blood sample for CBC and provide ORS packets on tomorrow morning visit.',
    assigned_worker: 'Anitha K.',
    status: 'delivered_to_worker',
    created_at: '2026-09-25T11:40:00Z'
  },
  {
    id: 'task-3',
    user_id: 'u-105',
    patient_name: 'Suresh Patil',
    village: 'Pattikonda',
    priority: 'High',
    missing_data_fields: ['Fasting Lipid Profile', 'Urine Albumin'],
    reason: 'Random sugar 265 mg/dL with diabetic neuropathy symptoms.',
    recommended_action: 'Worker Sunita B. to ensure patient attends NCD clinic this Tuesday for comprehensive screening.',
    assigned_worker: 'Sunita B.',
    status: 'pending',
    created_at: '2026-09-22T08:50:00Z'
  }
];

export const INITIAL_CONFLICTS: ConflictRecord[] = [
  {
    id: 'cnf-1',
    user_id: 'u-101',
    patient_name: 'Ramesh Kumar',
    field_name: 'Provisional Diagnosis',
    local_value: 'Stage 2 Hypertension with Angina Pectoris',
    remote_value: 'Essential Hypertension with Chronic Gastritis',
    local_source: 'ASHA Lakshmi P. (Field Tablet Sync)',
    remote_source: 'Dr. Arvind Sharma (CHC Portal)',
    local_timestamp: '2026-09-20T10:00:00Z',
    remote_timestamp: '2026-09-20T14:30:00Z',
    status: 'unresolved'
  }
];
